### ISSUE TITLE
Client timeout

### ISSUE THREAD

**Issue by misisnik** [schollz/find3#17]
"Post http://localhost:8002/classify: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" sometimes occur when http://127.0.0.1:8005/api/v1/by_location/magnetometer_and_wifi04

**Comment by schollz** [comment]
Could you share your database?

**Comment by misisnik** [comment]
Yes for example this one
https://drive.google.com/file/d/18J75ydKUhA8hXd_zaH84w_GMLUdJlIAX/view?usp=sharing

**Comment by schollz** [comment]
Thanks @misisnik. The problem was that Linear SVM scales very very badly for your data, probably something to do with the decomposition of your data since you have one axis that is positive, magnetometer, while the rest are negative. I just added a timeout (6fba702feec9e35aab7da9d21fe6ceb4fe232682) which will skip bad machine learning algorithms that take too long (>10 seconds).

As for accuracy, having one less machine learning algorithm won't make a huge difference. The classification scheme uses meta-learning, so it uses all the algorithms - and while the more the better, having one less won't hurt too much. Anyways, I see that your accuracy is pretty high when leaving that one out.
