### ISSUE TITLE
Add API endpoint with Unix Time in milliseconds

### ISSUE THREAD

**Issue by DatanoiseTV** [schollz/find3#40]
For the ESP8266, there seems to be no reliable way to get Unix time in microseconds.
At least, I had no success with NTP.

@schollz Could you provide an API-Endpoint like /time which returns Unix server time in microseconds? Currently I am running my own microservice for it: https://unixtimeservice.herokuapp.com/

**Comment by schollz** [comment]
I can do that, sure.

But, maybe it would be more effective to have the server assign the timestamp in this case? I could have the `/data` route check if the timestamp is `0`, and if so it could set it as the current time in the server. I didn't do this by default because I wanted to support cases where you could take fingerprints over time and then submit them in bulk to the server (and have their timestamps preserved).

**Comment by DatanoiseTV** [comment]
@schollz I agree, and that was also one of my ideas. Maybe you can implement both, just in case?

**Comment by schollz** [comment]
@DatanoiseTV  Yep, both are added now. Here you can get the current timestamp: https://cloud.internalpositioning.com/now

Also you can submit fingerprints without a timestamp and they will be inserted into the server. The only caveat here is that if two fingerprints are somehow inserted at exactly the same time (millisecond) they will overwrite one another. I think this is very very unlikely though
