### ISSUE TITLE
A.I. calibration produces inaccerate numbers

### ISSUE THREAD

**Issue by Thomas499** [schollz/find3#60]
Also, does the a.i. progressively get smarter with each calibration? I noticed that one day all the rooms were in the blue then three days later 3 rooms were in red and 4 were in green. I know when it calibrates it keeps 30% of the data separate to run as a test, but still these numbers seem unusual. 

What is even more unusual is that the real results appear to be much less accurate than the numbers produced by the dashboard.

**Comment by schollz** [comment]
@Thomas499 If you are still refering to your database with ~56 total points, this is probably due to a very few amount of points. When the database re-calibrates upon re-learning it will use a new set of cross-validation points for learning/testing. If you have only ~15 points per location then this set will have high variance between calibrations.
