### ISSUE TITLE
Unable to calibrate data

### ISSUE THREAD

**Issue by kappelloss** [schollz/find3#71]
Hello,
I've installed Find3-Server on a Windows machine with docker. I can access the Dashboard and send data from my android phone to the server (when I start learning from my phone there is a .db file added to the data Folder which I set when run the docker Container). But the Dashboard always says that there is no data for learning avaliable and I when I call the API with the calibrate command for my familiy I always get an error...
The previous Version 2.x is running like charm on the same Setup....

**Comment by schollz** [comment]
It sounds like you don't have learning fingerprints. Check the database.

```
sqlite3 YOURDB.sqlite3.db "select * from sensors where locationid != ''"
```

That should return something. If it doesn't, then you aren't sending learning fingerprints to your server correctly.

**Comment by kappelloss** [comment]
In addtion, running the test Suite (Family testdb) is giving the same error... The inserts are working like charm (success=true), but when I want to acess the data via Dashboard it says no avaliable data for learning... Same Problem with the API....

**Comment by misisnik** [comment]
I have the similar problem on the newest docker version, when I downgrade for 8days old image it works (I do not have time today to solve it I just need to plot some graphs into my thesis so i downgrade it into the version which works. So maybe tomorrow i will check it.

**Comment by schollz** [comment]
@misisnik @kappelloss The issue was with the `base58` library I was using which released a new version three days ago https://github.com/keis/base58/releases/tag/v1.0.0.

This new version converts to bytes instead of strings, so I've fixed my code to accommodate it here: https://github.com/schollz/find3/commit/84dc111c8281cc0ca8bbcca610d4a4830c9cf230.

It's likely that this will fix all the issues here. You can rebuild the docker image yourself or wait about an hour to pull the latest from the hub.
