### ISSUE TITLE
MQTT Can't connect

### ISSUE THREAD

**Issue by seaverd** [schollz/find3#91]
Is it possible that a recent change broke mqtt connectivity?  I see your edits from yesterday are regarding mqtt.  I am new to find3 and am running it on my unraid server in docker.    I have it behind letsencrypt in a reverse proxy.  To be honest I am just getting started with find3 but because it needs docker in the same container and home assistant only allows 1 mqtt connection I have been running all my mqtt messages through the mqtt instance in your docker.  Everything was fine till the docker container updated yesterday.

**Comment by schollz** [comment]
Actually, the changes yesterday were to fix them. The MQTT wasn't using the write configuration folder, so now there is a flag to force it to use the configuration folder in the `/data` directory. 

Its possible that its not working for you because its now using a different directory for MQTT credentials. Can you try reloading your credentials (just ` http GET localhost:8015/api/v1/mqtt/YOURFAMILY`)?

If that doesn't work, try doing the steps in #90: https://github.com/schollz/find3/issues/90#issuecomment-390605888 and report back in that issue if it doesn't work for you.
